### ISSUE TITLE
[Bug]: Application Error on Heroku

### ISSUE THREAD

**Issue by naikmubashir** [thenameisajay/Pioneers-in-Computer-Science#8]
### Description
An error occurred while trying to access the live link of the project . The error message displayed is: **"Application Error: An error occurred in the application and your page could not be served."**

### Steps to Reproduce
1. Try accessing the live link of the project.

### Expected Behavior
The application should load and display the project as expected.

### Actual Behavior
The application fails to load, showing an "Application Error" message.
<img width="1306" alt="Screenshot 2024-10-11 at 23 18 18" src="https://github.com/user-attachments/assets/35719050-5706-4d0e-8dfb-3954dda6dc06">

### Logs
Run the following command to view the logs:
```bash
heroku logs --tail

**Comment by thenameisajay** [comment]
Hi @naikmubashir ,

Thank you so much for your interest in this project—I truly appreciate it.

I’ve taken note of the issue you raised and wanted to provide some context regarding the current status of the site. After careful consideration, I decided to take it down, primarily for two reasons:

1. **Deployment Strategy Update**: Initially, when I developed this project as part of my dissertation, my priority was on rapid deployment and quick setup, which made Heroku an ideal choice despite its cost. However, now that my focus has shifted, I’ve explored other deployment options that offer similar benefits without the constraints of the $5 Eco dyno plan. If you’d like to run the project locally, the setup instructions in the README.md should guide you through the process. I’d be more than happy to assist you with any issues you encounter during this setup.

2. **Project Evolution**: While revisiting this project with a plan for redeployment, I recognized areas that could be significantly improved. What **once represented my best work now feels like a stepping stone to something more refined**. I am actively working on a new and improved version that aims to be more informative and interactive. I’m hopeful to have it completed by the end of the year and will certainly release it when it's ready.

If you’re still interested in this journey, I’d love for you to stay in touch. Feel free to reach out if you have any further questions or if there’s anything else I can assist you with.
